### ISSUE TITLE
BUG: `rc` command freezes when an invalid directory is passed

### ISSUE THREAD

**Issue by arnavthorat78** [B-Kernel/bkernel#53]
When running the `rc` command in B-Kernel, passing an invalid path (e.g. a path that does not exist), it will just freeze the entire application. The only way to exit the application is by pressing <kbd>Ctrl</kbd> + <kbd>C</kbd>.

However, this is a bit annoying, since you have to start up the application again. This can be fixed easily by just doing a check like:

```py
import os.path

if not os.path.isfile(filename): # <--- Your filename here
  print_error("0x0000") # Some error code
else:
  # Run your normal code
```

**Comment by EriktheRDev** [comment]
It doesn't crash for me

**Comment by arnavthorat78** [comment]
**FIX:** Run the command as an administrator in Windows; and as root user in Linux/macOS using the `sudo` command.
